# Generated by Django 5.1.6 on 2025-02-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Soccer', 'Soccer'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('sport', models.ManyToManyField(to='championship.sports')),
            ],
        ),
    ]
